### ISSUE TITLE
correlated_genes_enrichment_error_1

### ISSUE THREAD

**Issue by alessandrolaferlita** [alaimos/tRFexplorer#1]
![correlated_genes_enrichment_error_1](https://user-images.githubusercontent.com/45789805/206292827-0102dd3c-92a3-47dd-b0b3-4b72fef25abb.png)

**Comment by alessandrolaferlita** [comment]
I was doing a correlated genes enrichment of tRF-16-078SUXD and I found this error.

**Comment by alaimos** [comment]
Closing this issue since this is not a real issue. The online alpha version does not use the latest docker image which already includes the ClusterProfiler package.
