### ISSUE TITLE
Diff. Surv Analysis [ TCGA-SARC] Dedifferentiated Liposarcoma Error

### ISSUE THREAD

**Issue by alessandrolaferlita** [alaimos/tRFexplorer#8]
![diff_surv_error_1](https://user-images.githubusercontent.com/45789805/209167140-d617a922-1db5-47a6-aaf8-f9af56a1394f.png)

I found this error when I tried to run a differential survival analysis on Dedifferentiate Liposarcoma cohort

**Comment by alaimos** [comment]
A not updated data cache caused the issue.
The data cache has now been updated, and the error disappeared.
